spring.application.name=batch342
# ===============================
# = DATA SOURCE
# ===============================
# Set here configuration for localhost port
# (sesuaikan dengan port yg kalian ingin gunakan)
server.port=9001 
# Set here configurations for the database connection
# (sesuaikan dengan nama db kalian masing2)
spring.datasource.url=jdbc:postgresql://localhost:5432/spring342app
#  (sesuaikan username psql kalian masing2)
spring.datasource.username=postgres
#  (sesuaikan pwd psql kalian masing2)
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults= false
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
# spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
#  (berguna untuk melihat query yg tereksekusi di dalam log)
spring.jpa.show-sql=true
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.hibernate.ddl-auto=update